version: '2' 
services:
  web:
    dockerfile: app.dockerfile
    build: flask-app
    ports:
     - "5000:5000"
    volumes:
     - .:/code
  mysql:
    dockerfile: db.dockerfile
    build: mysql-serv
    environment:
      MYSQL_DATABASE: flaskapp
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: 0.0.0.0
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
